language: node_js
node_js:
- '7'

before_deploy:
 - npm run build

deploy:
  provider: firebase
  token:
    secure: "kvqcoMBymKIUJUzRlplbbQkF8JrXTDAShQMEWbEkpOWb5AUGD0ls8mzWN5wcwE5yM5ZEpto3zJUGs/5Kn5UQMSie0FdL/ST6hftegcd1OKnZaZbtEYobf1KBDzyxRPEJFQOWiQqjIi8+ovFAUbyqNQLtuYty0Ms3QZJ/JnZYmSBNFVonvwYQYAzkSCYRzAtyj5sjR/qbhA8TXYadtQf2HSIDSidaWLQ20+sM5hCiEHmJiLrOFxOOW1AO95kNGPFUZrMUXSU33tsKxAIw2U6Kjbk/eKh0lOq3SE9jf+f0SMZGWTa6J+UVXAqylA4psYOIL29ZFcdxO8UPEKWESBB0rHneC3JBGZe4sAwFKy4P2seWkG0z3hqZpbXVU5NeerWynb5a1iFvRcNF+eQdnXtgatB05v6WrvwVSZahYdAeH0T8VeoIigMg1hjXs8rRRoIiH5gesOfVuj8BkgBpFgrHkZAWJ37S5n4eNunH7wwcbpA3oaj3CI/fnL5SGUr10KFNSeEI0sjDnZjWrkg3EVCtfmD6UgjKfgZmIN/OO5HgH7ptGkfkn487i91PAfK3tW4PIyAIKQNi+Md9EYQ3XKcJ42DqA1WFr93pU6CJBM+94aFKHNlDD3QNATePZa00Gr2Oc3Al3eYmhCz3RHH6Her+s3NIjVRu0ykvZWXSbZIA/Us="
